[colors.primary]
background = "#000000"

[font]
size = 9

[font.normal]
style = "Regular"

[window]
dynamic_padding = false
dynamic_title =true
opacity = 0.6
title = "Alacritty"

[window.padding]
x = 6
y = 6

